/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storage.v2019_04_01.implementation;

import java.util.List;
import com.microsoft.azure.management.storage.v2019_04_01.FileShareItem;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response schema. Contains list of shares returned, and if paging is
 * requested or required, a URL to next page of shares.
 */
public class FileShareItemsInner {
    /**
     * List of file shares returned.
     */
    @JsonProperty(value = "value", access = JsonProperty.Access.WRITE_ONLY)
    private List<FileShareItem> value;

    /**
     * Request URL that can be used to query next page of shares. Returned when
     * total number of requested shares exceed maximum page size.
     */
    @JsonProperty(value = "nextLink", access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /**
     * Get list of file shares returned.
     *
     * @return the value value
     */
    public List<FileShareItem> value() {
        return this.value;
    }

    /**
     * Get request URL that can be used to query next page of shares. Returned when total number of requested shares exceed maximum page size.
     *
     * @return the nextLink value
     */
    public String nextLink() {
        return this.nextLink;
    }

}
