// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicelinker.models;

import com.azure.core.annotation.Fluent;
import com.azure.resourcemanager.servicelinker.fluent.models.ConfigurationNameItemInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Configuration Name list which will be set based on different target resource, client type, auth type.
 */
@Fluent
public final class ConfigurationNameResult {
    /*
     * Expected configuration names for each target service.
     */
    @JsonProperty(value = "value")
    private List<ConfigurationNameItemInner> value;

    /*
     * Link to next page of resources.
     */
    @JsonProperty(value = "nextLink", access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /**
     * Creates an instance of ConfigurationNameResult class.
     */
    public ConfigurationNameResult() {
    }

    /**
     * Get the value property: Expected configuration names for each target service.
     * 
     * @return the value value.
     */
    public List<ConfigurationNameItemInner> value() {
        return this.value;
    }

    /**
     * Set the value property: Expected configuration names for each target service.
     * 
     * @param value the value value to set.
     * @return the ConfigurationNameResult object itself.
     */
    public ConfigurationNameResult withValue(List<ConfigurationNameItemInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Link to next page of resources.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() != null) {
            value().forEach(e -> e.validate());
        }
    }
}
