// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicelinker.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The extra auth info required by Database AAD authentication.
 */
@Fluent
public class DatabaseAadAuthInfo {
    /*
     * Username created in the database which is mapped to a user in AAD.
     */
    @JsonProperty(value = "userName")
    private String username;

    /**
     * Creates an instance of DatabaseAadAuthInfo class.
     */
    public DatabaseAadAuthInfo() {
    }

    /**
     * Get the username property: Username created in the database which is mapped to a user in AAD.
     * 
     * @return the username value.
     */
    public String username() {
        return this.username;
    }

    /**
     * Set the username property: Username created in the database which is mapped to a user in AAD.
     * 
     * @param username the username value to set.
     * @return the DatabaseAadAuthInfo object itself.
     */
    public DatabaseAadAuthInfo withUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
