// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicelinker.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The parameters of the dryrun.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "actionName",
    defaultImpl = DryrunParameters.class)
@JsonTypeName("DryrunParameters")
@JsonSubTypes({ @JsonSubTypes.Type(name = "createOrUpdate", value = CreateOrUpdateDryrunParameters.class) })
@Immutable
public class DryrunParameters {
    /**
     * Creates an instance of DryrunParameters class.
     */
    public DryrunParameters() {
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
