// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.servicelinker.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeId;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The authentication info when authType is EasyAuth Microsoft Entra ID.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "authType",
    defaultImpl = EasyAuthMicrosoftEntraIdAuthInfo.class,
    visible = true)
@JsonTypeName("easyAuthMicrosoftEntraID")
@Fluent
public final class EasyAuthMicrosoftEntraIdAuthInfo extends AuthInfoBase {
    /*
     * The authentication type.
     */
    @JsonTypeId
    @JsonProperty(value = "authType", required = true)
    private AuthType authType = AuthType.EASY_AUTH_MICROSOFT_ENTRA_ID;

    /*
     * Application clientId for EasyAuth Microsoft Entra ID.
     */
    @JsonProperty(value = "clientId")
    private String clientId;

    /*
     * Application Secret for EasyAuth Microsoft Entra ID.
     */
    @JsonProperty(value = "secret")
    private String secret;

    /*
     * Indicates whether to clean up previous operation when Linker is updating or deleting
     */
    @JsonProperty(value = "deleteOrUpdateBehavior")
    private DeleteOrUpdateBehavior deleteOrUpdateBehavior;

    /**
     * Creates an instance of EasyAuthMicrosoftEntraIdAuthInfo class.
     */
    public EasyAuthMicrosoftEntraIdAuthInfo() {
    }

    /**
     * Get the authType property: The authentication type.
     * 
     * @return the authType value.
     */
    @Override
    public AuthType authType() {
        return this.authType;
    }

    /**
     * Get the clientId property: Application clientId for EasyAuth Microsoft Entra ID.
     * 
     * @return the clientId value.
     */
    public String clientId() {
        return this.clientId;
    }

    /**
     * Set the clientId property: Application clientId for EasyAuth Microsoft Entra ID.
     * 
     * @param clientId the clientId value to set.
     * @return the EasyAuthMicrosoftEntraIdAuthInfo object itself.
     */
    public EasyAuthMicrosoftEntraIdAuthInfo withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * Get the secret property: Application Secret for EasyAuth Microsoft Entra ID.
     * 
     * @return the secret value.
     */
    public String secret() {
        return this.secret;
    }

    /**
     * Set the secret property: Application Secret for EasyAuth Microsoft Entra ID.
     * 
     * @param secret the secret value to set.
     * @return the EasyAuthMicrosoftEntraIdAuthInfo object itself.
     */
    public EasyAuthMicrosoftEntraIdAuthInfo withSecret(String secret) {
        this.secret = secret;
        return this;
    }

    /**
     * Get the deleteOrUpdateBehavior property: Indicates whether to clean up previous operation when Linker is updating
     * or deleting.
     * 
     * @return the deleteOrUpdateBehavior value.
     */
    public DeleteOrUpdateBehavior deleteOrUpdateBehavior() {
        return this.deleteOrUpdateBehavior;
    }

    /**
     * Set the deleteOrUpdateBehavior property: Indicates whether to clean up previous operation when Linker is updating
     * or deleting.
     * 
     * @param deleteOrUpdateBehavior the deleteOrUpdateBehavior value to set.
     * @return the EasyAuthMicrosoftEntraIdAuthInfo object itself.
     */
    public EasyAuthMicrosoftEntraIdAuthInfo withDeleteOrUpdateBehavior(DeleteOrUpdateBehavior deleteOrUpdateBehavior) {
        this.deleteOrUpdateBehavior = deleteOrUpdateBehavior;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EasyAuthMicrosoftEntraIdAuthInfo withAuthMode(AuthMode authMode) {
        super.withAuthMode(authMode);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
