/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.quota.v2019_07_19;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.management.quota.v2019_07_19.implementation.QuotaRequestDetailsInner;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.quota.v2019_07_19.implementation.CapacityManager;
import org.joda.time.DateTime;
import java.util.List;

/**
 * Type representing LocationProviderQuotaRequestDetails.
 */
public interface LocationProviderQuotaRequestDetails extends HasInner<QuotaRequestDetailsInner>, HasManager<CapacityManager> {
    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the message value.
     */
    String message();

    /**
     * @return the requestStatus value.
     */
    Object requestStatus();

    /**
     * @return the requestSubmitTime value.
     */
    DateTime requestSubmitTime();

    /**
     * @return the value value.
     */
    List<SubRequest> value();

}
