# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/resources/ci.yml
      - sdk/resources/azure-resourcemanager-resources-generated/
    exclude:
      - sdk/resources/pom.xml
      - sdk/resources/azure-resourcemanager-resources-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/resources/ci.yml
      - sdk/resources/azure-resourcemanager-resources-generated/
    exclude:
      - sdk/resources/pom.xml
      - sdk/resources/azure-resourcemanager-resources-generated/pom.xml

parameters:
  - name: release_azureresourcemanagerresourcesgenerated
    displayName: azure-resourcemanager-resources-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: resources
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-resources-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerresourcesgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagerresourcesgenerated }}
