# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/network/ci.yml
      - sdk/network/azure-resourcemanager-network-generated/
    exclude:
      - sdk/network/pom.xml
      - sdk/network/azure-resourcemanager-network-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/network/ci.yml
      - sdk/network/azure-resourcemanager-network-generated/
    exclude:
      - sdk/network/pom.xml
      - sdk/network/azure-resourcemanager-network-generated/pom.xml

parameters:
  - name: release_azureresourcemanagernetworkgenerated
    displayName: azure-resourcemanager-network-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: network
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-network-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagernetworkgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagernetworkgenerated }}
