// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * Artifacts container info.
 */
@Immutable
public final class ArtifactsContainerInfo {
    /*
     * This is a SAS URI to an Azure Storage Container that contains the test run artifacts.
     */
    @Generated
    @JsonProperty(value = "url")
    private String url;

    /*
     * Expiry time of the container (RFC 3339 literal format)
     */
    @Generated
    @JsonProperty(value = "expireDateTime")
    private OffsetDateTime expireDateTime;

    /**
     * Creates an instance of ArtifactsContainerInfo class.
     */
    @Generated
    private ArtifactsContainerInfo() {
    }

    /**
     * Get the url property: This is a SAS URI to an Azure Storage Container that contains the test run artifacts.
     * 
     * @return the url value.
     */
    @Generated
    public String getUrl() {
        return this.url;
    }

    /**
     * Get the expireDateTime property: Expiry time of the container (RFC 3339 literal format).
     * 
     * @return the expireDateTime value.
     */
    @Generated
    public OffsetDateTime getExpireDateTime() {
        return this.expireDateTime;
    }
}
