// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Auto stop criteria for a test. This will automatically stop a load test if the error percentage is high for a
 * certain time window.
 */
@Fluent
public final class AutoStopCriteria {
    /*
     * Whether auto-stop should be disabled. The default value is false.
     */
    @Generated
    @JsonProperty(value = "autoStopDisabled")
    private Boolean autoStopDisabled;

    /*
     * Threshold percentage of errors on which test run should be automatically stopped. Allowed values are in range of
     * 0.0-100.0
     */
    @Generated
    @JsonProperty(value = "errorRate")
    private Double errorRate;

    /*
     * Time window during which the error percentage should be evaluated in seconds.
     */
    @Generated
    @JsonProperty(value = "errorRateTimeWindowInSeconds")
    private Integer errorRateTimeWindowInSeconds;

    /**
     * Creates an instance of AutoStopCriteria class.
     */
    @Generated
    public AutoStopCriteria() {
    }

    /**
     * Get the autoStopDisabled property: Whether auto-stop should be disabled. The default value is false.
     * 
     * @return the autoStopDisabled value.
     */
    @Generated
    public Boolean isAutoStopDisabled() {
        return this.autoStopDisabled;
    }

    /**
     * Set the autoStopDisabled property: Whether auto-stop should be disabled. The default value is false.
     * 
     * @param autoStopDisabled the autoStopDisabled value to set.
     * @return the AutoStopCriteria object itself.
     */
    @Generated
    public AutoStopCriteria setAutoStopDisabled(Boolean autoStopDisabled) {
        this.autoStopDisabled = autoStopDisabled;
        return this;
    }

    /**
     * Get the errorRate property: Threshold percentage of errors on which test run should be automatically stopped.
     * Allowed values are in range of 0.0-100.0.
     * 
     * @return the errorRate value.
     */
    @Generated
    public Double getErrorRate() {
        return this.errorRate;
    }

    /**
     * Set the errorRate property: Threshold percentage of errors on which test run should be automatically stopped.
     * Allowed values are in range of 0.0-100.0.
     * 
     * @param errorRate the errorRate value to set.
     * @return the AutoStopCriteria object itself.
     */
    @Generated
    public AutoStopCriteria setErrorRate(Double errorRate) {
        this.errorRate = errorRate;
        return this;
    }

    /**
     * Get the errorRateTimeWindowInSeconds property: Time window during which the error percentage should be evaluated
     * in seconds.
     * 
     * @return the errorRateTimeWindowInSeconds value.
     */
    @Generated
    public Integer getErrorRateTimeWindowInSeconds() {
        return this.errorRateTimeWindowInSeconds;
    }

    /**
     * Set the errorRateTimeWindowInSeconds property: Time window during which the error percentage should be evaluated
     * in seconds.
     * 
     * @param errorRateTimeWindowInSeconds the errorRateTimeWindowInSeconds value to set.
     * @return the AutoStopCriteria object itself.
     */
    @Generated
    public AutoStopCriteria setErrorRateTimeWindowInSeconds(Integer errorRateTimeWindowInSeconds) {
        this.errorRateTimeWindowInSeconds = errorRateTimeWindowInSeconds;
        return this;
    }
}
