// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The input artifacts for the test.
 */
@Immutable
public final class TestInputArtifacts {
    /*
     * File info
     */
    @Generated
    @JsonProperty(value = "configFileInfo")
    private TestFileInfo configFileInfo;

    /*
     * File info
     */
    @Generated
    @JsonProperty(value = "testScriptFileInfo")
    private TestFileInfo testScriptFileInfo;

    /*
     * File info
     */
    @Generated
    @JsonProperty(value = "userPropFileInfo")
    private TestFileInfo userPropFileInfo;

    /*
     * File info
     */
    @Generated
    @JsonProperty(value = "inputArtifactsZipFileInfo")
    private TestFileInfo inputArtifactsZipFileInfo;

    /*
     * The config json file for url based test
     */
    @Generated
    @JsonProperty(value = "urlTestConfigFileInfo")
    private TestFileInfo urlTestConfigFileInfo;

    /*
     * Additional supported files for the test run
     */
    @Generated
    @JsonProperty(value = "additionalFileInfo", access = JsonProperty.Access.WRITE_ONLY)
    private List<TestFileInfo> additionalFileInfo;

    /**
     * Creates an instance of TestInputArtifacts class.
     */
    @Generated
    private TestInputArtifacts() {
    }

    /**
     * Get the configFileInfo property: File info.
     * 
     * @return the configFileInfo value.
     */
    @Generated
    public TestFileInfo getConfigFileInfo() {
        return this.configFileInfo;
    }

    /**
     * Get the testScriptFileInfo property: File info.
     * 
     * @return the testScriptFileInfo value.
     */
    @Generated
    public TestFileInfo getTestScriptFileInfo() {
        return this.testScriptFileInfo;
    }

    /**
     * Get the userPropFileInfo property: File info.
     * 
     * @return the userPropFileInfo value.
     */
    @Generated
    public TestFileInfo getUserPropFileInfo() {
        return this.userPropFileInfo;
    }

    /**
     * Get the inputArtifactsZipFileInfo property: File info.
     * 
     * @return the inputArtifactsZipFileInfo value.
     */
    @Generated
    public TestFileInfo getInputArtifactsZipFileInfo() {
        return this.inputArtifactsZipFileInfo;
    }

    /**
     * Get the urlTestConfigFileInfo property: The config json file for url based test.
     * 
     * @return the urlTestConfigFileInfo value.
     */
    @Generated
    public TestFileInfo getUrlTestConfigFileInfo() {
        return this.urlTestConfigFileInfo;
    }

    /**
     * Get the additionalFileInfo property: Additional supported files for the test run.
     * 
     * @return the additionalFileInfo value.
     */
    @Generated
    public List<TestFileInfo> getAdditionalFileInfo() {
        return this.additionalFileInfo;
    }
}
