// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * Test run file info.
 */
@Immutable
public final class TestRunFileInfo {
    /*
     * Name of the file.
     */
    @Generated
    @JsonProperty(value = "fileName", access = JsonProperty.Access.WRITE_ONLY)
    private String fileName;

    /*
     * File URL.
     */
    @Generated
    @JsonProperty(value = "url", access = JsonProperty.Access.WRITE_ONLY)
    private String url;

    /*
     * File type
     */
    @Generated
    @JsonProperty(value = "fileType", access = JsonProperty.Access.WRITE_ONLY)
    private FileType fileType;

    /*
     * Expiry time of the file (RFC 3339 literal format)
     */
    @Generated
    @JsonProperty(value = "expireDateTime", access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime expireDateTime;

    /*
     * Validation status of the file
     */
    @Generated
    @JsonProperty(value = "validationStatus", access = JsonProperty.Access.WRITE_ONLY)
    private FileStatus validationStatus;

    /*
     * Validation failure error details
     */
    @Generated
    @JsonProperty(value = "validationFailureDetails", access = JsonProperty.Access.WRITE_ONLY)
    private String validationFailureDetails;

    /**
     * Creates an instance of TestRunFileInfo class.
     */
    @Generated
    private TestRunFileInfo() {
    }

    /**
     * Get the fileName property: Name of the file.
     * 
     * @return the fileName value.
     */
    @Generated
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Get the url property: File URL.
     * 
     * @return the url value.
     */
    @Generated
    public String getUrl() {
        return this.url;
    }

    /**
     * Get the fileType property: File type.
     * 
     * @return the fileType value.
     */
    @Generated
    public FileType getFileType() {
        return this.fileType;
    }

    /**
     * Get the expireDateTime property: Expiry time of the file (RFC 3339 literal format).
     * 
     * @return the expireDateTime value.
     */
    @Generated
    public OffsetDateTime getExpireDateTime() {
        return this.expireDateTime;
    }

    /**
     * Get the validationStatus property: Validation status of the file.
     * 
     * @return the validationStatus value.
     */
    @Generated
    public FileStatus getValidationStatus() {
        return this.validationStatus;
    }

    /**
     * Get the validationFailureDetails property: Validation failure error details.
     * 
     * @return the validationFailureDetails value.
     */
    @Generated
    public String getValidationFailureDetails() {
        return this.validationFailureDetails;
    }
}
