// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The output artifacts for the test run.
 */
@Immutable
public final class TestRunOutputArtifacts {
    /*
     * File info
     */
    @Generated
    @JsonProperty(value = "resultFileInfo")
    private TestRunFileInfo resultFileInfo;

    /*
     * File info
     */
    @Generated
    @JsonProperty(value = "logsFileInfo")
    private TestRunFileInfo logsFileInfo;

    /*
     * The container for test run artifacts.
     */
    @Generated
    @JsonProperty(value = "artifactsContainerInfo")
    private ArtifactsContainerInfo artifactsContainerInfo;

    /**
     * Creates an instance of TestRunOutputArtifacts class.
     */
    @Generated
    private TestRunOutputArtifacts() {
    }

    /**
     * Get the resultFileInfo property: File info.
     * 
     * @return the resultFileInfo value.
     */
    @Generated
    public TestRunFileInfo getResultFileInfo() {
        return this.resultFileInfo;
    }

    /**
     * Get the logsFileInfo property: File info.
     * 
     * @return the logsFileInfo value.
     */
    @Generated
    public TestRunFileInfo getLogsFileInfo() {
        return this.logsFileInfo;
    }

    /**
     * Get the artifactsContainerInfo property: The container for test run artifacts.
     * 
     * @return the artifactsContainerInfo value.
     */
    @Generated
    public ArtifactsContainerInfo getArtifactsContainerInfo() {
        return this.artifactsContainerInfo;
    }
}
