/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.datalakeanalytics.v2015_10_01_preview;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The OperationMetaMetricAvailabilitiesSpecification model.
 */
public class OperationMetaMetricAvailabilitiesSpecification {
    /**
     * The timegrain for OperationMetaMetricAvailabilitiesSpecification.
     */
    @JsonProperty(value = "timeGrain")
    private String timeGrain;

    /**
     * The blobDuration for OperationMetaMetricAvailabilitiesSpecification.
     */
    @JsonProperty(value = "blobDuration")
    private String blobDuration;

    /**
     * Get the timegrain for OperationMetaMetricAvailabilitiesSpecification.
     *
     * @return the timeGrain value
     */
    public String timeGrain() {
        return this.timeGrain;
    }

    /**
     * Set the timegrain for OperationMetaMetricAvailabilitiesSpecification.
     *
     * @param timeGrain the timeGrain value to set
     * @return the OperationMetaMetricAvailabilitiesSpecification object itself.
     */
    public OperationMetaMetricAvailabilitiesSpecification withTimeGrain(String timeGrain) {
        this.timeGrain = timeGrain;
        return this;
    }

    /**
     * Get the blobDuration for OperationMetaMetricAvailabilitiesSpecification.
     *
     * @return the blobDuration value
     */
    public String blobDuration() {
        return this.blobDuration;
    }

    /**
     * Set the blobDuration for OperationMetaMetricAvailabilitiesSpecification.
     *
     * @param blobDuration the blobDuration value to set
     * @return the OperationMetaMetricAvailabilitiesSpecification object itself.
     */
    public OperationMetaMetricAvailabilitiesSpecification withBlobDuration(String blobDuration) {
        this.blobDuration = blobDuration;
        return this;
    }

}
