// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.security.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * List of pricing configurations response.
 */
@Fluent
public final class PricingListAutoGeneratedInner {
    /*
     * List of pricing configurations
     */
    @JsonProperty(value = "value", required = true)
    private List<PricingAutoGeneratedInner> value;

    /**
     * Creates an instance of PricingListAutoGeneratedInner class.
     */
    public PricingListAutoGeneratedInner() {
    }

    /**
     * Get the value property: List of pricing configurations.
     * 
     * @return the value value.
     */
    public List<PricingAutoGeneratedInner> value() {
        return this.value;
    }

    /**
     * Set the value property: List of pricing configurations.
     * 
     * @param value the value value to set.
     * @return the PricingListAutoGeneratedInner object itself.
     */
    public PricingListAutoGeneratedInner withValue(List<PricingAutoGeneratedInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() == null) {
            throw LOGGER.logExceptionAsError(
                new IllegalArgumentException("Missing required property value in model PricingListAutoGeneratedInner"));
        } else {
            value().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(PricingListAutoGeneratedInner.class);
}
