// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * This package contains the implementation classes for MicrosoftCapacity.
 * Microsoft Azure Quota Resource Provider.
 */
package com.microsoft.azure.management.quota.v2019_07_19.implementation;
