/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.quota.v2019_07_19.implementation;

import retrofit2.Retrofit;
import com.google.common.reflect.TypeToken;
import com.microsoft.azure.AzureServiceFuture;
import com.microsoft.azure.ListOperationCallback;
import com.microsoft.azure.management.quota.v2019_07_19.ExceptionResponseException;
import com.microsoft.azure.Page;
import com.microsoft.azure.PagedList;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;
import java.util.List;
import okhttp3.ResponseBody;
import retrofit2.http.GET;
import retrofit2.http.Header;
import retrofit2.http.Headers;
import retrofit2.http.Path;
import retrofit2.http.Query;
import retrofit2.http.Url;
import retrofit2.Response;
import rx.functions.Func1;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in Quotas.
 */
public class QuotasInner {
    /** The Retrofit service to perform REST calls. */
    private QuotasService service;
    /** The service client containing this operation class. */
    private MicrosoftCapacityImpl client;

    /**
     * Initializes an instance of QuotasInner.
     *
     * @param retrofit the Retrofit instance built from a Retrofit Builder.
     * @param client the instance of the service client containing this operation class.
     */
    public QuotasInner(Retrofit retrofit, MicrosoftCapacityImpl client) {
        this.service = retrofit.create(QuotasService.class);
        this.client = client;
    }

    /**
     * The interface defining all the services for Quotas to be
     * used by Retrofit to perform actually REST calls.
     */
    interface QuotasService {
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.quota.v2019_07_19.Quotas listStatus" })
        @GET("subscriptions/{subscriptionId}/providers/Microsoft.Capacity/providers/{providerId}/locations/{location}/serviceLimits")
        Observable<Response<ResponseBody>> listStatus(@Path("subscriptionId") String subscriptionId, @Path("providerId") String providerId, @Path("location") String location, @Query("api-version") String apiVersion, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.quota.v2019_07_19.Quotas listStatusNext" })
        @GET
        Observable<Response<ResponseBody>> listStatusNext(@Url String nextUrl, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param providerId Azure resource Provider id.
     * @param location Azure region.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ExceptionResponseException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;CurrentQuotaLimitInner&gt; object if successful.
     */
    public PagedList<CurrentQuotaLimitInner> listStatus(final String providerId, final String location) {
        ServiceResponse<Page<CurrentQuotaLimitInner>> response = listStatusSinglePageAsync(providerId, location).toBlocking().single();
        return new PagedList<CurrentQuotaLimitInner>(response.body()) {
            @Override
            public Page<CurrentQuotaLimitInner> nextPage(String nextPageLink) {
                return listStatusNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param providerId Azure resource Provider id.
     * @param location Azure region.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<CurrentQuotaLimitInner>> listStatusAsync(final String providerId, final String location, final ListOperationCallback<CurrentQuotaLimitInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listStatusSinglePageAsync(providerId, location),
            new Func1<String, Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> call(String nextPageLink) {
                    return listStatusNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param providerId Azure resource Provider id.
     * @param location Azure region.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CurrentQuotaLimitInner&gt; object
     */
    public Observable<Page<CurrentQuotaLimitInner>> listStatusAsync(final String providerId, final String location) {
        return listStatusWithServiceResponseAsync(providerId, location)
            .map(new Func1<ServiceResponse<Page<CurrentQuotaLimitInner>>, Page<CurrentQuotaLimitInner>>() {
                @Override
                public Page<CurrentQuotaLimitInner> call(ServiceResponse<Page<CurrentQuotaLimitInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param providerId Azure resource Provider id.
     * @param location Azure region.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CurrentQuotaLimitInner&gt; object
     */
    public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> listStatusWithServiceResponseAsync(final String providerId, final String location) {
        return listStatusSinglePageAsync(providerId, location)
            .concatMap(new Func1<ServiceResponse<Page<CurrentQuotaLimitInner>>, Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> call(ServiceResponse<Page<CurrentQuotaLimitInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listStatusNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
    ServiceResponse<PageImpl<CurrentQuotaLimitInner>> * @param providerId Azure resource Provider id.
    ServiceResponse<PageImpl<CurrentQuotaLimitInner>> * @param location Azure region.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;CurrentQuotaLimitInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> listStatusSinglePageAsync(final String providerId, final String location) {
        if (this.client.subscriptionId() == null) {
            throw new IllegalArgumentException("Parameter this.client.subscriptionId() is required and cannot be null.");
        }
        if (providerId == null) {
            throw new IllegalArgumentException("Parameter providerId is required and cannot be null.");
        }
        if (location == null) {
            throw new IllegalArgumentException("Parameter location is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        return service.listStatus(this.client.subscriptionId(), providerId, location, this.client.apiVersion(), this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<CurrentQuotaLimitInner>> result = listStatusDelegate(response);
                        return Observable.just(new ServiceResponse<Page<CurrentQuotaLimitInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<PageImpl<CurrentQuotaLimitInner>> listStatusDelegate(Response<ResponseBody> response) throws ExceptionResponseException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<PageImpl<CurrentQuotaLimitInner>, ExceptionResponseException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<PageImpl<CurrentQuotaLimitInner>>() { }.getType())
                .registerError(ExceptionResponseException.class)
                .build(response);
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ExceptionResponseException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;CurrentQuotaLimitInner&gt; object if successful.
     */
    public PagedList<CurrentQuotaLimitInner> listStatusNext(final String nextPageLink) {
        ServiceResponse<Page<CurrentQuotaLimitInner>> response = listStatusNextSinglePageAsync(nextPageLink).toBlocking().single();
        return new PagedList<CurrentQuotaLimitInner>(response.body()) {
            @Override
            public Page<CurrentQuotaLimitInner> nextPage(String nextPageLink) {
                return listStatusNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @param serviceFuture the ServiceFuture object tracking the Retrofit calls
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<CurrentQuotaLimitInner>> listStatusNextAsync(final String nextPageLink, final ServiceFuture<List<CurrentQuotaLimitInner>> serviceFuture, final ListOperationCallback<CurrentQuotaLimitInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listStatusNextSinglePageAsync(nextPageLink),
            new Func1<String, Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> call(String nextPageLink) {
                    return listStatusNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CurrentQuotaLimitInner&gt; object
     */
    public Observable<Page<CurrentQuotaLimitInner>> listStatusNextAsync(final String nextPageLink) {
        return listStatusNextWithServiceResponseAsync(nextPageLink)
            .map(new Func1<ServiceResponse<Page<CurrentQuotaLimitInner>>, Page<CurrentQuotaLimitInner>>() {
                @Override
                public Page<CurrentQuotaLimitInner> call(ServiceResponse<Page<CurrentQuotaLimitInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CurrentQuotaLimitInner&gt; object
     */
    public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> listStatusNextWithServiceResponseAsync(final String nextPageLink) {
        return listStatusNextSinglePageAsync(nextPageLink)
            .concatMap(new Func1<ServiceResponse<Page<CurrentQuotaLimitInner>>, Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> call(ServiceResponse<Page<CurrentQuotaLimitInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listStatusNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Gets the current quota limit and usages for the resources provider for the specified location.
     * This API gets the current quota limit and usages for the resources provider for the specified location. This response can be used to submit quotaRequests.
     *
    ServiceResponse<PageImpl<CurrentQuotaLimitInner>> * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;CurrentQuotaLimitInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> listStatusNextSinglePageAsync(final String nextPageLink) {
        if (nextPageLink == null) {
            throw new IllegalArgumentException("Parameter nextPageLink is required and cannot be null.");
        }
        String nextUrl = String.format("%s", nextPageLink);
        return service.listStatusNext(nextUrl, this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CurrentQuotaLimitInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<CurrentQuotaLimitInner>> result = listStatusNextDelegate(response);
                        return Observable.just(new ServiceResponse<Page<CurrentQuotaLimitInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<PageImpl<CurrentQuotaLimitInner>> listStatusNextDelegate(Response<ResponseBody> response) throws ExceptionResponseException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<PageImpl<CurrentQuotaLimitInner>, ExceptionResponseException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<PageImpl<CurrentQuotaLimitInner>>() { }.getType())
                .registerError(ExceptionResponseException.class)
                .build(response);
    }

}
