// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.contoso.widgetmanager.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * Faked shared model.
 */
@Immutable
public final class FakedSharedModel {
    /*
     * The tag.
     */
    @Generated
    @JsonProperty(value = "tag")
    private String tag;

    /*
     * The created date.
     */
    @Generated
    @JsonProperty(value = "createdAt")
    private OffsetDateTime createdAt;

    /**
     * Creates an instance of FakedSharedModel class.
     * 
     * @param tag the tag value to set.
     * @param createdAt the createdAt value to set.
     */
    @Generated
    @JsonCreator
    public FakedSharedModel(@JsonProperty(value = "tag") String tag,
        @JsonProperty(value = "createdAt") OffsetDateTime createdAt) {
        this.tag = tag;
        this.createdAt = createdAt;
    }

    /**
     * Get the tag property: The tag.
     * 
     * @return the tag value.
     */
    @Generated
    public String getTag() {
        return this.tag;
    }

    /**
     * Get the createdAt property: The created date.
     * 
     * @return the createdAt value.
     */
    @Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
}
