/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.appplatform.v2019_05_01_preview;

import rx.Observable;
import com.microsoft.azure.management.appplatform.v2019_05_01_preview.implementation.ServicesTestsInner;
import com.microsoft.azure.arm.model.HasInner;

/**
 * Type representing ServicesTests.
 */
public interface ServicesTests extends HasInner<ServicesTestsInner> {
    /**
     * Get a Service and its properties.
     *
     * @param resourceGroupName The name of the resource group that contains the resource. You can obtain this value from the Azure Resource Manager API or the portal.
     * @param serviceName The name of the Service resource.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<ServiceResource> getByResourceGroupAsync(String resourceGroupName, String serviceName);

}
