// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.appconfiguration.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Telemetry settings.
 */
@Fluent
public final class TelemetryProperties {
    /*
     * Resource ID of a resource enabling telemetry collection
     */
    @JsonProperty(value = "resourceId")
    private String resourceId;

    /**
     * Creates an instance of TelemetryProperties class.
     */
    public TelemetryProperties() {
    }

    /**
     * Get the resourceId property: Resource ID of a resource enabling telemetry collection.
     * 
     * @return the resourceId value.
     */
    public String resourceId() {
        return this.resourceId;
    }

    /**
     * Set the resourceId property: Resource ID of a resource enabling telemetry collection.
     * 
     * @param resourceId the resourceId value to set.
     * @return the TelemetryProperties object itself.
     */
    public TelemetryProperties withResourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
