# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/sql/ci.yml
      - sdk/sql/azure-resourcemanager-sql-generated/
    exclude:
      - sdk/sql/pom.xml
      - sdk/sql/azure-resourcemanager-sql-generated/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/sql/ci.yml
      - sdk/sql/azure-resourcemanager-sql-generated/
    exclude:
      - sdk/sql/pom.xml
      - sdk/sql/azure-resourcemanager-sql-generated/pom.xml

parameters:
  - name: release_azureresourcemanagersqlgenerated
    displayName: azure-resourcemanager-sql-generated
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: sql
    EnableBatchRelease: true
    Artifacts:
      - name: azure-resourcemanager-sql-generated
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagersqlgenerated
        releaseInBatch: ${{ parameters.release_azureresourcemanagersqlgenerated }}
