/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.synapse.v2019_06_01_preview;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.management.synapse.v2019_06_01_preview.implementation.LibraryResourceInner;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.synapse.v2019_06_01_preview.implementation.SynapseManager;

/**
 * Type representing LibraryResource.
 */
public interface LibraryResource extends HasInner<LibraryResourceInner>, HasManager<SynapseManager> {
    /**
     * @return the creatorId value.
     */
    String creatorId();

    /**
     * @return the etag value.
     */
    String etag();

    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the libraryResourceName value.
     */
    String libraryResourceName();

    /**
     * @return the libraryResourceType value.
     */
    String libraryResourceType();

    /**
     * @return the name value.
     */
    String name();

    /**
     * @return the path value.
     */
    String path();

    /**
     * @return the provisioningStatus value.
     */
    String provisioningStatus();

    /**
     * @return the type value.
     */
    String type();

    /**
     * @return the uploadedTimestamp value.
     */
    String uploadedTimestamp();

}
