// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.ProxyResource;
import com.azure.core.management.SystemData;
import com.azure.resourcemanager.agrifood.models.SolutionProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Solution resource.
 */
@Fluent
public final class SolutionInner extends ProxyResource {
    /*
     * Solution resource properties.
     */
    @JsonProperty(value = "properties")
    private SolutionProperties properties;

    /*
     * The ETag value to implement optimistic concurrency.
     */
    @JsonProperty(value = "eTag", access = JsonProperty.Access.WRITE_ONLY)
    private String etag;

    /*
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    @JsonProperty(value = "systemData", access = JsonProperty.Access.WRITE_ONLY)
    private SystemData systemData;

    /**
     * Creates an instance of SolutionInner class.
     */
    public SolutionInner() {
    }

    /**
     * Get the properties property: Solution resource properties.
     * 
     * @return the properties value.
     */
    public SolutionProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties property: Solution resource properties.
     * 
     * @param properties the properties value to set.
     * @return the SolutionInner object itself.
     */
    public SolutionInner withProperties(SolutionProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the etag property: The ETag value to implement optimistic concurrency.
     * 
     * @return the etag value.
     */
    public String etag() {
        return this.etag;
    }

    /**
     * Get the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    public SystemData systemData() {
        return this.systemData;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (properties() != null) {
            properties().validate();
        }
    }
}
