// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.apicenter.models;

import com.azure.core.annotation.Immutable;
import com.azure.resourcemanager.apicenter.fluent.models.ApiInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * API collection
 * 
 * Paginated collection of APIs.
 */
@Immutable
public final class ApiCollection {
    /*
     * Page items.
     */
    @JsonProperty(value = "value", access = JsonProperty.Access.WRITE_ONLY)
    private List<ApiInner> value;

    /*
     * The link to the next page of items
     */
    @JsonProperty(value = "nextLink", access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /**
     * Creates an instance of ApiCollection class.
     */
    public ApiCollection() {
    }

    /**
     * Get the value property: Page items.
     * 
     * @return the value value.
     */
    public List<ApiInner> value() {
        return this.value;
    }

    /**
     * Get the nextLink property: The link to the next page of items.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() != null) {
            value().forEach(e -> e.validate());
        }
    }
}
