// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.apicenter.models;

import com.azure.core.http.rest.Response;
import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.apicenter.fluent.models.ApiDefinitionInner;

/**
 * An immutable client-side representation of ApiDefinition.
 */
public interface ApiDefinition {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     * 
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     * 
     * @return the type value.
     */
    String type();

    /**
     * Gets the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the title property: API definition title.
     * 
     * @return the title value.
     */
    String title();

    /**
     * Gets the description property: API definition description.
     * 
     * @return the description value.
     */
    String description();

    /**
     * Gets the specification property: API specification details.
     * 
     * @return the specification value.
     */
    ApiDefinitionPropertiesSpecification specification();

    /**
     * Gets the name of the resource group.
     * 
     * @return the name of the resource group.
     */
    String resourceGroupName();

    /**
     * Gets the inner com.azure.resourcemanager.apicenter.fluent.models.ApiDefinitionInner object.
     * 
     * @return the inner object.
     */
    ApiDefinitionInner innerModel();

    /**
     * The entirety of the ApiDefinition definition.
     */
    interface Definition
        extends DefinitionStages.Blank, DefinitionStages.WithParentResource, DefinitionStages.WithCreate {
    }

    /**
     * The ApiDefinition definition stages.
     */
    interface DefinitionStages {
        /**
         * The first stage of the ApiDefinition definition.
         */
        interface Blank extends WithParentResource {
        }

        /**
         * The stage of the ApiDefinition definition allowing to specify parent resource.
         */
        interface WithParentResource {
            /**
             * Specifies resourceGroupName, serviceName, workspaceName, apiName, versionName.
             * 
             * @param resourceGroupName The name of the resource group. The name is case insensitive.
             * @param serviceName The name of Azure API Center service.
             * @param workspaceName The name of the workspace.
             * @param apiName The name of the API.
             * @param versionName The name of the API version.
             * @return the next definition stage.
             */
            WithCreate withExistingVersion(String resourceGroupName, String serviceName, String workspaceName,
                String apiName, String versionName);
        }

        /**
         * The stage of the ApiDefinition definition which contains all the minimum required properties for the resource
         * to be created, but also allows for any other optional properties to be specified.
         */
        interface WithCreate extends DefinitionStages.WithTitle, DefinitionStages.WithDescription {
            /**
             * Executes the create request.
             * 
             * @return the created resource.
             */
            ApiDefinition create();

            /**
             * Executes the create request.
             * 
             * @param context The context to associate with this operation.
             * @return the created resource.
             */
            ApiDefinition create(Context context);
        }

        /**
         * The stage of the ApiDefinition definition allowing to specify title.
         */
        interface WithTitle {
            /**
             * Specifies the title property: API definition title..
             * 
             * @param title API definition title.
             * @return the next definition stage.
             */
            WithCreate withTitle(String title);
        }

        /**
         * The stage of the ApiDefinition definition allowing to specify description.
         */
        interface WithDescription {
            /**
             * Specifies the description property: API definition description..
             * 
             * @param description API definition description.
             * @return the next definition stage.
             */
            WithCreate withDescription(String description);
        }
    }

    /**
     * Begins update for the ApiDefinition resource.
     * 
     * @return the stage of resource update.
     */
    ApiDefinition.Update update();

    /**
     * The template for ApiDefinition update.
     */
    interface Update extends UpdateStages.WithTitle, UpdateStages.WithDescription {
        /**
         * Executes the update request.
         * 
         * @return the updated resource.
         */
        ApiDefinition apply();

        /**
         * Executes the update request.
         * 
         * @param context The context to associate with this operation.
         * @return the updated resource.
         */
        ApiDefinition apply(Context context);
    }

    /**
     * The ApiDefinition update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the ApiDefinition update allowing to specify title.
         */
        interface WithTitle {
            /**
             * Specifies the title property: API definition title..
             * 
             * @param title API definition title.
             * @return the next definition stage.
             */
            Update withTitle(String title);
        }

        /**
         * The stage of the ApiDefinition update allowing to specify description.
         */
        interface WithDescription {
            /**
             * Specifies the description property: API definition description..
             * 
             * @param description API definition description.
             * @return the next definition stage.
             */
            Update withDescription(String description);
        }
    }

    /**
     * Refreshes the resource to sync with Azure.
     * 
     * @return the refreshed resource.
     */
    ApiDefinition refresh();

    /**
     * Refreshes the resource to sync with Azure.
     * 
     * @param context The context to associate with this operation.
     * @return the refreshed resource.
     */
    ApiDefinition refresh(Context context);

    /**
     * Import API specification
     * 
     * Imports the API specification.
     * 
     * @param payload The API specification source entity.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link Response}.
     */
    Response<Void> importSpecificationWithResponse(ApiSpecImportRequest payload, Context context);

    /**
     * Import API specification
     * 
     * Imports the API specification.
     * 
     * @param payload The API specification source entity.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    void importSpecification(ApiSpecImportRequest payload);

    /**
     * Export API specification
     * 
     * Exports the API specification.
     * 
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the API specification export result along with {@link Response}.
     */
    Response<ApiSpecExportResult> exportSpecificationWithResponse(Context context);

    /**
     * Export API specification
     * 
     * Exports the API specification.
     * 
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the API specification export result.
     */
    ApiSpecExportResult exportSpecification();
}
