// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.apicenter.models;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.apicenter.fluent.models.DeploymentInner;

/**
 * An immutable client-side representation of Deployment.
 */
public interface Deployment {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     * 
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     * 
     * @return the type value.
     */
    String type();

    /**
     * Gets the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the title property: API deployment title.
     * 
     * @return the title value.
     */
    String title();

    /**
     * Gets the description property: Description
     * 
     * Description of the deployment.
     * 
     * @return the description value.
     */
    String description();

    /**
     * Gets the environmentId property: API center-scoped environment resource ID.
     * 
     * @return the environmentId value.
     */
    String environmentId();

    /**
     * Gets the definitionId property: API center-scoped definition resource ID.
     * 
     * @return the definitionId value.
     */
    String definitionId();

    /**
     * Gets the state property: State
     * 
     * State of API deployment.
     * 
     * @return the state value.
     */
    DeploymentState state();

    /**
     * Gets the server property: Server.
     * 
     * @return the server value.
     */
    DeploymentServer server();

    /**
     * Gets the customProperties property: The custom metadata defined for API catalog entities.
     * 
     * @return the customProperties value.
     */
    Object customProperties();

    /**
     * Gets the name of the resource group.
     * 
     * @return the name of the resource group.
     */
    String resourceGroupName();

    /**
     * Gets the inner com.azure.resourcemanager.apicenter.fluent.models.DeploymentInner object.
     * 
     * @return the inner object.
     */
    DeploymentInner innerModel();

    /**
     * The entirety of the Deployment definition.
     */
    interface Definition
        extends DefinitionStages.Blank, DefinitionStages.WithParentResource, DefinitionStages.WithCreate {
    }

    /**
     * The Deployment definition stages.
     */
    interface DefinitionStages {
        /**
         * The first stage of the Deployment definition.
         */
        interface Blank extends WithParentResource {
        }

        /**
         * The stage of the Deployment definition allowing to specify parent resource.
         */
        interface WithParentResource {
            /**
             * Specifies resourceGroupName, serviceName, workspaceName, apiName.
             * 
             * @param resourceGroupName The name of the resource group. The name is case insensitive.
             * @param serviceName The name of Azure API Center service.
             * @param workspaceName The name of the workspace.
             * @param apiName The name of the API.
             * @return the next definition stage.
             */
            WithCreate withExistingApi(String resourceGroupName, String serviceName, String workspaceName,
                String apiName);
        }

        /**
         * The stage of the Deployment definition which contains all the minimum required properties for the resource to
         * be created, but also allows for any other optional properties to be specified.
         */
        interface WithCreate extends DefinitionStages.WithTitle, DefinitionStages.WithDescription,
            DefinitionStages.WithEnvironmentId, DefinitionStages.WithDefinitionId, DefinitionStages.WithState,
            DefinitionStages.WithServer, DefinitionStages.WithCustomProperties {
            /**
             * Executes the create request.
             * 
             * @return the created resource.
             */
            Deployment create();

            /**
             * Executes the create request.
             * 
             * @param context The context to associate with this operation.
             * @return the created resource.
             */
            Deployment create(Context context);
        }

        /**
         * The stage of the Deployment definition allowing to specify title.
         */
        interface WithTitle {
            /**
             * Specifies the title property: API deployment title.
             * 
             * @param title API deployment title.
             * @return the next definition stage.
             */
            WithCreate withTitle(String title);
        }

        /**
         * The stage of the Deployment definition allowing to specify description.
         */
        interface WithDescription {
            /**
             * Specifies the description property: Description
             * 
             * Description of the deployment..
             * 
             * @param description Description
             * 
             * Description of the deployment.
             * @return the next definition stage.
             */
            WithCreate withDescription(String description);
        }

        /**
         * The stage of the Deployment definition allowing to specify environmentId.
         */
        interface WithEnvironmentId {
            /**
             * Specifies the environmentId property: API center-scoped environment resource ID..
             * 
             * @param environmentId API center-scoped environment resource ID.
             * @return the next definition stage.
             */
            WithCreate withEnvironmentId(String environmentId);
        }

        /**
         * The stage of the Deployment definition allowing to specify definitionId.
         */
        interface WithDefinitionId {
            /**
             * Specifies the definitionId property: API center-scoped definition resource ID..
             * 
             * @param definitionId API center-scoped definition resource ID.
             * @return the next definition stage.
             */
            WithCreate withDefinitionId(String definitionId);
        }

        /**
         * The stage of the Deployment definition allowing to specify state.
         */
        interface WithState {
            /**
             * Specifies the state property: State
             * 
             * State of API deployment..
             * 
             * @param state State
             * 
             * State of API deployment.
             * @return the next definition stage.
             */
            WithCreate withState(DeploymentState state);
        }

        /**
         * The stage of the Deployment definition allowing to specify server.
         */
        interface WithServer {
            /**
             * Specifies the server property: Server.
             * 
             * @param server Server.
             * @return the next definition stage.
             */
            WithCreate withServer(DeploymentServer server);
        }

        /**
         * The stage of the Deployment definition allowing to specify customProperties.
         */
        interface WithCustomProperties {
            /**
             * Specifies the customProperties property: The custom metadata defined for API catalog entities..
             * 
             * @param customProperties The custom metadata defined for API catalog entities.
             * @return the next definition stage.
             */
            WithCreate withCustomProperties(Object customProperties);
        }
    }

    /**
     * Begins update for the Deployment resource.
     * 
     * @return the stage of resource update.
     */
    Deployment.Update update();

    /**
     * The template for Deployment update.
     */
    interface Update extends UpdateStages.WithTitle, UpdateStages.WithDescription, UpdateStages.WithEnvironmentId,
        UpdateStages.WithDefinitionId, UpdateStages.WithState, UpdateStages.WithServer,
        UpdateStages.WithCustomProperties {
        /**
         * Executes the update request.
         * 
         * @return the updated resource.
         */
        Deployment apply();

        /**
         * Executes the update request.
         * 
         * @param context The context to associate with this operation.
         * @return the updated resource.
         */
        Deployment apply(Context context);
    }

    /**
     * The Deployment update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the Deployment update allowing to specify title.
         */
        interface WithTitle {
            /**
             * Specifies the title property: API deployment title.
             * 
             * @param title API deployment title.
             * @return the next definition stage.
             */
            Update withTitle(String title);
        }

        /**
         * The stage of the Deployment update allowing to specify description.
         */
        interface WithDescription {
            /**
             * Specifies the description property: Description
             * 
             * Description of the deployment..
             * 
             * @param description Description
             * 
             * Description of the deployment.
             * @return the next definition stage.
             */
            Update withDescription(String description);
        }

        /**
         * The stage of the Deployment update allowing to specify environmentId.
         */
        interface WithEnvironmentId {
            /**
             * Specifies the environmentId property: API center-scoped environment resource ID..
             * 
             * @param environmentId API center-scoped environment resource ID.
             * @return the next definition stage.
             */
            Update withEnvironmentId(String environmentId);
        }

        /**
         * The stage of the Deployment update allowing to specify definitionId.
         */
        interface WithDefinitionId {
            /**
             * Specifies the definitionId property: API center-scoped definition resource ID..
             * 
             * @param definitionId API center-scoped definition resource ID.
             * @return the next definition stage.
             */
            Update withDefinitionId(String definitionId);
        }

        /**
         * The stage of the Deployment update allowing to specify state.
         */
        interface WithState {
            /**
             * Specifies the state property: State
             * 
             * State of API deployment..
             * 
             * @param state State
             * 
             * State of API deployment.
             * @return the next definition stage.
             */
            Update withState(DeploymentState state);
        }

        /**
         * The stage of the Deployment update allowing to specify server.
         */
        interface WithServer {
            /**
             * Specifies the server property: Server.
             * 
             * @param server Server.
             * @return the next definition stage.
             */
            Update withServer(DeploymentServer server);
        }

        /**
         * The stage of the Deployment update allowing to specify customProperties.
         */
        interface WithCustomProperties {
            /**
             * Specifies the customProperties property: The custom metadata defined for API catalog entities..
             * 
             * @param customProperties The custom metadata defined for API catalog entities.
             * @return the next definition stage.
             */
            Update withCustomProperties(Object customProperties);
        }
    }

    /**
     * Refreshes the resource to sync with Azure.
     * 
     * @return the refreshed resource.
     */
    Deployment refresh();

    /**
     * Refreshes the resource to sync with Azure.
     * 
     * @param context The context to associate with this operation.
     * @return the refreshed resource.
     */
    Deployment refresh(Context context);
}
