// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.apicenter.models;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.apicenter.fluent.models.EnvironmentInner;

/**
 * An immutable client-side representation of Environment.
 */
public interface Environment {
    /**
     * Gets the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    String id();

    /**
     * Gets the name property: The name of the resource.
     * 
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     * 
     * @return the type value.
     */
    String type();

    /**
     * Gets the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    SystemData systemData();

    /**
     * Gets the title property: Environment title.
     * 
     * @return the title value.
     */
    String title();

    /**
     * Gets the description property: Description.
     * 
     * @return the description value.
     */
    String description();

    /**
     * Gets the kind property: Environment kind.
     * 
     * @return the kind value.
     */
    EnvironmentKind kind();

    /**
     * Gets the server property: Server
     * 
     * Server information of the environment.
     * 
     * @return the server value.
     */
    EnvironmentServer server();

    /**
     * Gets the onboarding property: The onboarding property.
     * 
     * @return the onboarding value.
     */
    Onboarding onboarding();

    /**
     * Gets the customProperties property: The custom metadata defined for API catalog entities.
     * 
     * @return the customProperties value.
     */
    Object customProperties();

    /**
     * Gets the name of the resource group.
     * 
     * @return the name of the resource group.
     */
    String resourceGroupName();

    /**
     * Gets the inner com.azure.resourcemanager.apicenter.fluent.models.EnvironmentInner object.
     * 
     * @return the inner object.
     */
    EnvironmentInner innerModel();

    /**
     * The entirety of the Environment definition.
     */
    interface Definition
        extends DefinitionStages.Blank, DefinitionStages.WithParentResource, DefinitionStages.WithCreate {
    }

    /**
     * The Environment definition stages.
     */
    interface DefinitionStages {
        /**
         * The first stage of the Environment definition.
         */
        interface Blank extends WithParentResource {
        }

        /**
         * The stage of the Environment definition allowing to specify parent resource.
         */
        interface WithParentResource {
            /**
             * Specifies resourceGroupName, serviceName, workspaceName.
             * 
             * @param resourceGroupName The name of the resource group. The name is case insensitive.
             * @param serviceName The name of Azure API Center service.
             * @param workspaceName The name of the workspace.
             * @return the next definition stage.
             */
            WithCreate withExistingWorkspace(String resourceGroupName, String serviceName, String workspaceName);
        }

        /**
         * The stage of the Environment definition which contains all the minimum required properties for the resource
         * to be created, but also allows for any other optional properties to be specified.
         */
        interface WithCreate
            extends DefinitionStages.WithTitle, DefinitionStages.WithDescription, DefinitionStages.WithKind,
            DefinitionStages.WithServer, DefinitionStages.WithOnboarding, DefinitionStages.WithCustomProperties {
            /**
             * Executes the create request.
             * 
             * @return the created resource.
             */
            Environment create();

            /**
             * Executes the create request.
             * 
             * @param context The context to associate with this operation.
             * @return the created resource.
             */
            Environment create(Context context);
        }

        /**
         * The stage of the Environment definition allowing to specify title.
         */
        interface WithTitle {
            /**
             * Specifies the title property: Environment title..
             * 
             * @param title Environment title.
             * @return the next definition stage.
             */
            WithCreate withTitle(String title);
        }

        /**
         * The stage of the Environment definition allowing to specify description.
         */
        interface WithDescription {
            /**
             * Specifies the description property: Description..
             * 
             * @param description Description.
             * @return the next definition stage.
             */
            WithCreate withDescription(String description);
        }

        /**
         * The stage of the Environment definition allowing to specify kind.
         */
        interface WithKind {
            /**
             * Specifies the kind property: Environment kind..
             * 
             * @param kind Environment kind.
             * @return the next definition stage.
             */
            WithCreate withKind(EnvironmentKind kind);
        }

        /**
         * The stage of the Environment definition allowing to specify server.
         */
        interface WithServer {
            /**
             * Specifies the server property: Server
             * 
             * Server information of the environment..
             * 
             * @param server Server
             * 
             * Server information of the environment.
             * @return the next definition stage.
             */
            WithCreate withServer(EnvironmentServer server);
        }

        /**
         * The stage of the Environment definition allowing to specify onboarding.
         */
        interface WithOnboarding {
            /**
             * Specifies the onboarding property: The onboarding property..
             * 
             * @param onboarding The onboarding property.
             * @return the next definition stage.
             */
            WithCreate withOnboarding(Onboarding onboarding);
        }

        /**
         * The stage of the Environment definition allowing to specify customProperties.
         */
        interface WithCustomProperties {
            /**
             * Specifies the customProperties property: The custom metadata defined for API catalog entities..
             * 
             * @param customProperties The custom metadata defined for API catalog entities.
             * @return the next definition stage.
             */
            WithCreate withCustomProperties(Object customProperties);
        }
    }

    /**
     * Begins update for the Environment resource.
     * 
     * @return the stage of resource update.
     */
    Environment.Update update();

    /**
     * The template for Environment update.
     */
    interface Update extends UpdateStages.WithTitle, UpdateStages.WithDescription, UpdateStages.WithKind,
        UpdateStages.WithServer, UpdateStages.WithOnboarding, UpdateStages.WithCustomProperties {
        /**
         * Executes the update request.
         * 
         * @return the updated resource.
         */
        Environment apply();

        /**
         * Executes the update request.
         * 
         * @param context The context to associate with this operation.
         * @return the updated resource.
         */
        Environment apply(Context context);
    }

    /**
     * The Environment update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the Environment update allowing to specify title.
         */
        interface WithTitle {
            /**
             * Specifies the title property: Environment title..
             * 
             * @param title Environment title.
             * @return the next definition stage.
             */
            Update withTitle(String title);
        }

        /**
         * The stage of the Environment update allowing to specify description.
         */
        interface WithDescription {
            /**
             * Specifies the description property: Description..
             * 
             * @param description Description.
             * @return the next definition stage.
             */
            Update withDescription(String description);
        }

        /**
         * The stage of the Environment update allowing to specify kind.
         */
        interface WithKind {
            /**
             * Specifies the kind property: Environment kind..
             * 
             * @param kind Environment kind.
             * @return the next definition stage.
             */
            Update withKind(EnvironmentKind kind);
        }

        /**
         * The stage of the Environment update allowing to specify server.
         */
        interface WithServer {
            /**
             * Specifies the server property: Server
             * 
             * Server information of the environment..
             * 
             * @param server Server
             * 
             * Server information of the environment.
             * @return the next definition stage.
             */
            Update withServer(EnvironmentServer server);
        }

        /**
         * The stage of the Environment update allowing to specify onboarding.
         */
        interface WithOnboarding {
            /**
             * Specifies the onboarding property: The onboarding property..
             * 
             * @param onboarding The onboarding property.
             * @return the next definition stage.
             */
            Update withOnboarding(Onboarding onboarding);
        }

        /**
         * The stage of the Environment update allowing to specify customProperties.
         */
        interface WithCustomProperties {
            /**
             * Specifies the customProperties property: The custom metadata defined for API catalog entities..
             * 
             * @param customProperties The custom metadata defined for API catalog entities.
             * @return the next definition stage.
             */
            Update withCustomProperties(Object customProperties);
        }
    }

    /**
     * Refreshes the resource to sync with Azure.
     * 
     * @return the refreshed resource.
     */
    Environment refresh();

    /**
     * Refreshes the resource to sync with Azure.
     * 
     * @param context The context to associate with this operation.
     * @return the refreshed resource.
     */
    Environment refresh(Context context);
}
