// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.apicenter.implementation;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.apicenter.fluent.models.WorkspaceInner;
import com.azure.resourcemanager.apicenter.models.Workspace;

public final class WorkspaceImpl implements Workspace, Workspace.Definition, Workspace.Update {
    private WorkspaceInner innerObject;

    private final com.azure.resourcemanager.apicenter.ApiCenterManager serviceManager;

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public String title() {
        return this.innerModel().title();
    }

    public String description() {
        return this.innerModel().description();
    }

    public String resourceGroupName() {
        return resourceGroupName;
    }

    public WorkspaceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.apicenter.ApiCenterManager manager() {
        return this.serviceManager;
    }

    private String resourceGroupName;

    private String serviceName;

    private String workspaceName;

    public WorkspaceImpl withExistingService(String resourceGroupName, String serviceName) {
        this.resourceGroupName = resourceGroupName;
        this.serviceName = serviceName;
        return this;
    }

    public Workspace create() {
        this.innerObject = serviceManager.serviceClient().getWorkspaces()
            .createOrUpdateWithResponse(resourceGroupName, serviceName, workspaceName, this.innerModel(), Context.NONE)
            .getValue();
        return this;
    }

    public Workspace create(Context context) {
        this.innerObject = serviceManager.serviceClient().getWorkspaces()
            .createOrUpdateWithResponse(resourceGroupName, serviceName, workspaceName, this.innerModel(), context)
            .getValue();
        return this;
    }

    WorkspaceImpl(String name, com.azure.resourcemanager.apicenter.ApiCenterManager serviceManager) {
        this.innerObject = new WorkspaceInner();
        this.serviceManager = serviceManager;
        this.workspaceName = name;
    }

    public WorkspaceImpl update() {
        return this;
    }

    public Workspace apply() {
        this.innerObject = serviceManager.serviceClient().getWorkspaces()
            .createOrUpdateWithResponse(resourceGroupName, serviceName, workspaceName, this.innerModel(), Context.NONE)
            .getValue();
        return this;
    }

    public Workspace apply(Context context) {
        this.innerObject = serviceManager.serviceClient().getWorkspaces()
            .createOrUpdateWithResponse(resourceGroupName, serviceName, workspaceName, this.innerModel(), context)
            .getValue();
        return this;
    }

    WorkspaceImpl(WorkspaceInner innerObject, com.azure.resourcemanager.apicenter.ApiCenterManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
        this.resourceGroupName = Utils.getValueFromIdByName(innerObject.id(), "resourceGroups");
        this.serviceName = Utils.getValueFromIdByName(innerObject.id(), "services");
        this.workspaceName = Utils.getValueFromIdByName(innerObject.id(), "workspaces");
    }

    public Workspace refresh() {
        this.innerObject = serviceManager.serviceClient().getWorkspaces()
            .getWithResponse(resourceGroupName, serviceName, workspaceName, Context.NONE).getValue();
        return this;
    }

    public Workspace refresh(Context context) {
        this.innerObject = serviceManager.serviceClient().getWorkspaces()
            .getWithResponse(resourceGroupName, serviceName, workspaceName, context).getValue();
        return this;
    }

    public WorkspaceImpl withTitle(String title) {
        this.innerModel().withTitle(title);
        return this;
    }

    public WorkspaceImpl withDescription(String description) {
        this.innerModel().withDescription(description);
        return this;
    }
}
