// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Api properties.
 */
@Fluent
public final class ApiProperties {
    /*
     * Interval in minutes for which the weather data for the api needs to be refreshed.
     */
    @JsonProperty(value = "apiFreshnessTimeInMinutes")
    private Integer apiFreshnessTimeInMinutes;

    /**
     * Creates an instance of ApiProperties class.
     */
    public ApiProperties() {
    }

    /**
     * Get the apiFreshnessTimeInMinutes property: Interval in minutes for which the weather data for the api needs to
     * be refreshed.
     * 
     * @return the apiFreshnessTimeInMinutes value.
     */
    public Integer apiFreshnessTimeInMinutes() {
        return this.apiFreshnessTimeInMinutes;
    }

    /**
     * Set the apiFreshnessTimeInMinutes property: Interval in minutes for which the weather data for the api needs to
     * be refreshed.
     * 
     * @param apiFreshnessTimeInMinutes the apiFreshnessTimeInMinutes value to set.
     * @return the ApiProperties object itself.
     */
    public ApiProperties withApiFreshnessTimeInMinutes(Integer apiFreshnessTimeInMinutes) {
        this.apiFreshnessTimeInMinutes = apiFreshnessTimeInMinutes;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
