// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthCredentials abstract base class for Auth Purpose.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "kind",
    defaultImpl = AuthCredentials.class)
@JsonTypeName("AuthCredentials")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "ApiKeyAuthCredentials", value = ApiKeyAuthCredentials.class),
    @JsonSubTypes.Type(name = "OAuthClientCredentials", value = OAuthClientCredentials.class) })
@Immutable
public class AuthCredentials {
    /**
     * Creates an instance of AuthCredentials class.
     */
    public AuthCredentials() {
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
