// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.agrifood.fluent.models.DataConnectorInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Paged response contains list of requested objects and a URL link to get the next set of results.
 */
@Fluent
public final class DataConnectorListResponse {
    /*
     * List of requested objects.
     */
    @JsonProperty(value = "value", required = true)
    private List<DataConnectorInner> value;

    /*
     * Continuation link (absolute URI) to the next page of results in the list.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Creates an instance of DataConnectorListResponse class.
     */
    public DataConnectorListResponse() {
    }

    /**
     * Get the value property: List of requested objects.
     * 
     * @return the value value.
     */
    public List<DataConnectorInner> value() {
        return this.value;
    }

    /**
     * Set the value property: List of requested objects.
     * 
     * @param value the value value to set.
     * @return the DataConnectorListResponse object itself.
     */
    public DataConnectorListResponse withValue(List<DataConnectorInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Continuation link (absolute URI) to the next page of results in the list.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: Continuation link (absolute URI) to the next page of results in the list.
     * 
     * @param nextLink the nextLink value to set.
     * @return the DataConnectorListResponse object itself.
     */
    public DataConnectorListResponse withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() == null) {
            throw LOGGER.logExceptionAsError(
                new IllegalArgumentException("Missing required property value in model DataConnectorListResponse"));
        } else {
            value().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(DataConnectorListResponse.class);
}
