// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Extension Installation Request Body.
 */
@Fluent
public final class ExtensionInstallationRequest {
    /*
     * Extension Version.
     */
    @JsonProperty(value = "extensionVersion")
    private String extensionVersion;

    /*
     * Additional Api Properties.
     */
    @JsonProperty(value = "additionalApiProperties")
    @JsonInclude(value = JsonInclude.Include.NON_NULL, content = JsonInclude.Include.ALWAYS)
    private Map<String, ApiProperties> additionalApiProperties;

    /**
     * Creates an instance of ExtensionInstallationRequest class.
     */
    public ExtensionInstallationRequest() {
    }

    /**
     * Get the extensionVersion property: Extension Version.
     * 
     * @return the extensionVersion value.
     */
    public String extensionVersion() {
        return this.extensionVersion;
    }

    /**
     * Set the extensionVersion property: Extension Version.
     * 
     * @param extensionVersion the extensionVersion value to set.
     * @return the ExtensionInstallationRequest object itself.
     */
    public ExtensionInstallationRequest withExtensionVersion(String extensionVersion) {
        this.extensionVersion = extensionVersion;
        return this;
    }

    /**
     * Get the additionalApiProperties property: Additional Api Properties.
     * 
     * @return the additionalApiProperties value.
     */
    public Map<String, ApiProperties> additionalApiProperties() {
        return this.additionalApiProperties;
    }

    /**
     * Set the additionalApiProperties property: Additional Api Properties.
     * 
     * @param additionalApiProperties the additionalApiProperties value to set.
     * @return the ExtensionInstallationRequest object itself.
     */
    public ExtensionInstallationRequest
        withAdditionalApiProperties(Map<String, ApiProperties> additionalApiProperties) {
        this.additionalApiProperties = additionalApiProperties;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (additionalApiProperties() != null) {
            additionalApiProperties().values().forEach(e -> {
                if (e != null) {
                    e.validate();
                }
            });
        }
    }
}
